# Generated by Django 4.1 on 2022-11-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='emp_contact',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='emp_department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='emp_designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='emp_joinDate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
